"""added auth_id to employee and user table

Revision ID: 7acb597f3c69
Revises: 
Create Date: 2026-04-25 16:19:14.250515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7acb597f3c69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	# ## employees is a empty column
	op.add_column('employees', sa.Column(
		'is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
	op.add_column('employees', sa.Column('auth_id', sa.Integer(), nullable=False))
	
	op.create_index(op.f('ix_employees_auth_id'), 'employees', ['auth_id'], unique=True)
	
	with op.batch_alter_table('employees') as batch_op:
		op.create_foreign_key(
			"fk_employees_auth_id", 'user_auth', ['auth_id'], ['id'], ondelete='CASCADE')

	op.drop_column('employees', 'is_banned')
	op.drop_column('employees', 'username')
	op.drop_column('employees', 'password')
	op.drop_column('employees', 'email')
	
	op.add_column('users', 
		sa.Column('auth_id', sa.Integer(), nullable=True))

	op.execute(
	"""
		INSERT INTO user_auth (username, email, password, created_at, updated_at)
		SELECT username, email, password, created_at, updated_at FROM users;
	""")

	op.execute(
	"""
		UPDATE users
		SET auth_id = user_auth.id
		FROM user_auth
		WHERE users.username = user_auth.username
		  AND users.email = user_auth.email;
	""")
	
	op.create_index(op.f('ix_users_auth_id'), 'users', ['auth_id'], unique=True)
	
	with op.batch_alter_table('users') as batch_op:
		batch_op.create_foreign_key("fk_users_auth_id", 'user_auth', ['auth_id'], ['id'], ondelete='CASCADE')

	# todo: uncomment when i am moving from sqlite to pgsql/mysql
	# op.alter_column('users', 'auth_id', nullable = False)

	op.add_column('users', sa.Column(
		'is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
	
	op.add_column('users', sa.Column('first_name', 
		sa.String(length=20), nullable=False, server_default='empty'))
	
	op.add_column('users', sa.Column('last_name', 
		sa.String(length=20), nullable=False, server_default='empty'))
	
	op.add_column('users', sa.Column('phone_number', 
		sa.String(length=20), nullable=False, server_default='empty'))
	
	op.add_column('users', sa.Column('country', 
		sa.String(length=20), nullable=False, server_default='bd'))

	op.drop_column('users', 'email')
	op.drop_column('users', 'password')
	op.drop_column('users', 'username')
	op.drop_column('users', 'is_oauth_login')
	op.drop_column('users', 'is_banned')
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('users', 
		sa.Column('is_banned', sa.BOOLEAN(), nullable=False, server_default=sa.false()))
	op.add_column('users', sa.Column('is_oauth_login', sa.BOOLEAN(), nullable=False))
	op.add_column('users', sa.Column('username', sa.VARCHAR(length=15), nullable=False))
	op.add_column('users', sa.Column('password', sa.VARCHAR(length=150), nullable=True))
	op.add_column('users', sa.Column('email', sa.VARCHAR(length=50), nullable=False))
	
	op.drop_constraint(None, 'users', type_='foreignkey')
	op.drop_index(op.f('ix_users_auth_id'), table_name='users')
	
	op.drop_column('users', 'auth_id')
	op.drop_column('users', 'country')
	op.drop_column('users', 'phone_number')
	op.drop_column('users', 'last_name')
	op.drop_column('users', 'first_name')
	op.drop_column('users', 'is_active')
	
	op.add_column('employees', sa.Column('email', sa.VARCHAR(length=50), nullable=False))
	op.add_column('employees', sa.Column('password', sa.VARCHAR(length=100), nullable=True))
	op.add_column('employees', sa.Column('username', sa.VARCHAR(length=15), nullable=False))
	op.add_column('employees', sa.Column('is_banned', sa.BOOLEAN(), nullable=False))
	
	op.drop_constraint(None, 'employees', type_='foreignkey')
	op.drop_index(op.f('ix_employees_auth_id'), table_name='employees')
	op.drop_column('employees', 'auth_id')
	op.drop_column('employees', 'is_active')
	# ### end Alembic commands ###
